In [8]:
import numpy as np

my_array=np.arange(8)
my_array=np.arange(1, 8)
my_array=np.arange(-1, 8.5, 0.5)

print(my_array)
print(type(my_array))


[-1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5
  6.   6.5  7.   7.5  8. ]
<class 'numpy.ndarray'>


In [11]:
# Arrays from Lists
from_list = np.array([1,2,3], dtype=np.int8)
print(type(from_list[0]))


<class 'numpy.int8'>


In [20]:
# 2D Arrays
from_list = np.array([[1,2,3], [4,5,6]], dtype=np.int8)
array_2d = np.array((np.arange(0,8,2), np.arange(1,8,2)))

# For Shaping Array.
print(f"1D Shape:{my_array.shape} \n")
print(f"2D Shape:{array_2d.shape} \n")

# For ReShaping Array.
array_2d = array_2d.reshape((4, 2))  # Here we switched the row to columns
print(f"Reshaped Array: {array_2d} \n")

array_2d = array_2d.reshape(8)  # Reshaped to single Dimension array.
print(f"Reshaped Array: {array_2d} \n")

array_2d = array_2d.reshape((2,1,4))  # Reshape Even & ODD
print(f"Separate Even & ODD: {array_2d}\n")

array_2d = array_2d.reshape((2,2,2))
print(f"2_Dimensional Matrix: \n{array_2d}\n")

print(from_list)
print(type(from_list))


1D Shape:(19,) 

2D Shape:(2, 4) 

Reshaped Array: [[0 2]
 [4 6]
 [1 3]
 [5 7]] 

Reshaped Array: [0 2 4 6 1 3 5 7] 

Separate Even & ODD: [[[0 2 4 6]]

 [[1 3 5 7]]]

2_Dimensional Matrix: 
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [35]:
# Empty Arrays
empty_arr = np.zeros((2,2))
print(f"Zeros Array: \n{empty_arr}\n")
"'Empty and Zeros are not same Zeros make matrix Elements to zero while empty gives random elements as below.'"
empty_arr_one = np.ones((2,2))
empty_arr_one = np.empty((2,2,2))
print(f"Empty Array: \n{empty_arr_one}\n")

Zeros Array: 
[[0. 0.]
 [0. 0.]]

Empty Array: 
[[[0.0e+000 9.9e-324]
  [2.0e-323 3.0e-323]]

 [[4.9e-324 1.5e-323]
  [2.5e-323 3.5e-323]]]



In [52]:
# Eye Array
eye_array = np.eye(3, k=1)
print(f"Eye Array: \n{eye_array}\n")
eye_array[eye_array == 0] = 2
print(f"Replaced (0-2) Eye Array: \n{eye_array}\n")

eye_array[eye_array < 2 ] = 9
print(f"Replaced (Elements < 2 to 9) Eye Array: \n{eye_array}\n")
eye_array[0] = 3
print(f"Replaced entire row of Eye Array: \n{eye_array}\n")
eye_array[:2] = 3
print(f"Replaced 2 rows of Eye Array: \n{eye_array}\n")
eye_array[:, 0] = 4
print(f"Replaced entire column[1st] of Eye Array: \n{eye_array}\n")
eye_array[1:, :2] = 8
print(f"Replaced last rows and 2 columns of Eye Array: \n{eye_array}\n")


Eye Array: 
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

Replaced (0-2) Eye Array: 
[[2. 1. 2.]
 [2. 2. 1.]
 [2. 2. 2.]]

Replaced (Elements < 2 to 9) Eye Array: 
[[2. 9. 2.]
 [2. 2. 9.]
 [2. 2. 2.]]

Replaced entire row of Eye Array: 
[[3. 3. 3.]
 [2. 2. 9.]
 [2. 2. 2.]]

Replaced 2 rows of Eye Array: 
[[3. 3. 3.]
 [3. 3. 3.]
 [2. 2. 2.]]

Replaced entire column[1st] of Eye Array: 
[[4. 3. 3.]
 [4. 3. 3.]
 [4. 2. 2.]]

Replaced last rows and 2 columns of Eye Array: 
[[4. 3. 3.]
 [8. 8. 3.]
 [8. 8. 2.]]

Sorted Array: 
[[3. 3. 4.]
 [3. 8. 8.]
 [2. 8. 8.]]



In [56]:
# Sorting an Array.
sorted_array = np.sort(eye_array)
print(f"Sorted Array By Rows: \n{sorted_array}\n")

sorted_array = np.sort(eye_array, axis=0, kind="mergesort")
print(f"Sorted Array By Column: \n{sorted_array}\n")


Sorted Array By Rows: 
[[3. 3. 4.]
 [3. 8. 8.]
 [2. 8. 8.]]

Sorted Array By Column: 
[[4. 3. 2.]
 [8. 8. 3.]
 [8. 8. 3.]]



In [60]:
# Copy Array
my_view = sorted_array.view()
my_copy = sorted_array.copy()

my_view[:] = 4
print(f"{my_view}\n")
print(f"{sorted_array}\n")

my_copy[:] = 4
print(f"{my_copy}\n")
print(f"{sorted_array}")

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
